# Generated by Django 4.0.4 on 2022-05-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
