# Generated by Django 4.0.4 on 2022-05-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='payment',
        ),
    ]
