# Generated by Django 4.0.4 on 2022-05-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_brand_customer_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='brand',
        ),
        migrations.AddField(
            model_name='bill',
            name='brand',
            field=models.CharField(choices=[('company-1', 'company-1'), ('company-2', 'company-2'), ('company-3', 'company-3')], max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='bill',
            name='product',
        ),
        migrations.AddField(
            model_name='bill',
            name='product',
            field=models.ManyToManyField(to='app.product'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
