# Generated by Django 4.0.4 on 2022-05-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='brand',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Notpaid', 'Notpaid')], max_length=50, null=True),
        ),
    ]
