# Generated by Django 4.0.4 on 2022-05-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_bill_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='brand',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not-paid', 'Not-paid')], max_length=50, null=True),
        ),
    ]
