# Generated by Django 4.0.4 on 2022-05-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_bill_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='brand',
            new_name='payment',
        ),
    ]
