# Generated by Django 4.0.4 on 2022-05-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_bill_id_bill_bill_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_num',
        ),
        migrations.AddField(
            model_name='bill',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
